### ISSUE TITLE
Outdated Referee packet

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboCup-SSL/ssl-logtools#10]
Since the introduction of the gamecontroller the referee packet has changed a bit and this is not yet reflected in this repository. Fixing this would involve updating the proto packet definition and ensuring that everything remains backwards compatible.

**Comment by g3force** [comment]
As far as I can see in the code, the messages are only parsed to check their format. As all the protobuf messages are always downwards compatible, that should still work. The data is loaded and saved 1:1.

Besides, during last RoboCup, we used the ssl-go-tools, which also support the new tracking protocol.

**Comment by rolfvdhulst** [comment]
Ah, I was not aware that proto packets were backwards compatible in this way. That makes a lot of sense.
